import type { Metadata } from "next";
import "@/share/styles/destyle.css";
import "@/share/styles/global.scss";
import Header from '@/share/components/Header/Header';
import Footer from '@/share/components/Footer/Footer';
import Contact from "@/share/components/Contact/Contact";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
